/**
 * EnvProof - Generator Tests
 * Test .env.example generation
 */

import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { e, generateExample } from "../src/index.js";
import { writeExampleFile } from "../src/generator/index.js";

describe("generateExample", () => {
  it("generates basic example", () => {
    const schema = {
      API_KEY: e.string(),
    };

    const output = generateExample(schema);

    expect(output).toContain("API_KEY=");
    expect(output).toContain("# Required: yes");
  });

  it("marks optional variables", () => {
    const schema = {
      DEBUG: e.boolean().optional(),
    };

    const output = generateExample(schema);

    expect(output).toContain("# Required: no");
    expect(output).toContain("# DEBUG=");
  });

  it("shows default values", () => {
    const schema = {
      PORT: e.number().default(3000),
    };

    const output = generateExample(schema);

    expect(output).toContain("# Required: no (default: 3000)");
    expect(output).toContain("# PORT=");
  });

  it("includes descriptions", () => {
    const schema = {
      DATABASE_URL: e.url().description("PostgreSQL connection string"),
    };

    const output = generateExample(schema);

    expect(output).toContain("# PostgreSQL connection string");
  });

  it("shows enum options", () => {
    const schema = {
      NODE_ENV: e.enum(["development", "staging", "production"] as const),
    };

    const output = generateExample(schema);

    expect(output).toContain("# Options: development | staging | production");
  });

  it("warns about secrets", () => {
    const schema = {
      API_KEY: e.string().secret(),
    };

    const output = generateExample(schema);

    expect(output).toContain("# ⚠️  This is a secret");
  });

  it("uses secret placeholder value", () => {
    const schema = {
      API_KEY: e.string().secret(),
    };

    const output = generateExample(schema);

    expect(output).toContain("API_KEY=your_secret_here");
  });

  it("adds JSON format hint", () => {
    const schema = {
      CONFIG: e.json(),
    };

    const output = generateExample(schema);

    expect(output).toContain("# Format: JSON");
  });

  it("uses custom examples", () => {
    const schema = {
      DATABASE_URL: e.url().example("postgresql://user:pass@localhost:5432/db"),
    };

    const output = generateExample(schema);

    expect(output).toContain("postgresql://user:pass@localhost:5432/db");
  });

  it("includes header by default", () => {
    const schema = {
      PORT: e.number(),
    };

    const output = generateExample(schema);

    expect(output).toContain("# Environment Configuration");
    expect(output).toContain("# Generated by envproof");
  });

  it("can disable header", () => {
    const schema = {
      PORT: e.number(),
    };

    const output = generateExample(schema, { header: false });

    expect(output).not.toContain("# Environment Configuration");
  });

  it("supports custom header text", () => {
    const schema = {
      PORT: e.number(),
    };

    const output = generateExample(schema, { headerText: "# My App Config" });

    expect(output).toContain("# My App Config");
  });

  it("generates complete example", () => {
    const schema = {
      DATABASE_URL: e
        .url()
        .description("PostgreSQL connection string")
        .example("postgresql://user:pass@localhost:5432/db"),
      PORT: e.number().port().default(3000).description("Server port"),
      NODE_ENV: e
        .enum(["development", "staging", "production"] as const)
        .description("Application environment"),
      DEBUG: e.boolean().optional().description("Enable debug logging"),
      API_KEY: e.string().secret().description("External API key"),
    };

    const output = generateExample(schema);

    // Should have all variables
    expect(output).toContain("DATABASE_URL=");
    expect(output).toContain("PORT=");
    expect(output).toContain("NODE_ENV=");
    expect(output).toContain("DEBUG=");
    expect(output).toContain("API_KEY=");

    // Should have descriptions
    expect(output).toContain("# PostgreSQL connection string");
    expect(output).toContain("# Server port");
    expect(output).toContain("# Application environment");
    expect(output).toContain("# Enable debug logging");
    expect(output).toContain("# External API key");
  });

  it("writes example file to disk", () => {
    const schema = {
      PORT: e.number().default(3000),
    };
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "envproof-"));
    const outputPath = path.join(tempDir, ".env.example");

    const result = writeExampleFile(schema, { output: outputPath });

    expect(result.success).toBe(true);
    expect(fs.existsSync(outputPath)).toBe(true);
  });

  it("refuses to overwrite existing file without force", () => {
    const schema = {
      PORT: e.number().default(3000),
    };
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "envproof-"));
    const outputPath = path.join(tempDir, ".env.example");
    fs.writeFileSync(outputPath, "# existing", "utf-8");

    const result = writeExampleFile(schema, { output: outputPath });

    expect(result.success).toBe(false);
    expect(result.message).toContain("Use --force to overwrite");
  });
});
