/**
 * EnvKit - Example Generator
 * Generate .env.example files from schema
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { EnvSchema, GenerateOptions, AnySchema } from "../types.js";
import { BaseSchema } from "../schema/base.js";

/**
 * Generate .env.example content from a schema
 */
export function generateExampleContent<T extends EnvSchema>(
  schema: T,
  options: GenerateOptions = {}
): string {
  const lines: string[] = [];
  const { header = true, headerText } = options;

  // Header
  if (header) {
    lines.push(
      "# ============================================================"
    );
    lines.push(headerText ?? "# Environment Configuration");
    lines.push("# Generated by envkit");
    lines.push(
      "# ============================================================"
    );
    lines.push("");
  }

  // Process each variable
  for (const [key, fieldSchema] of Object.entries(schema)) {
    const schemaLines = generateVariableLines(key, fieldSchema as AnySchema);
    lines.push(...schemaLines);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate lines for a single variable
 */
function generateVariableLines(name: string, schema: AnySchema): string[] {
  const lines: string[] = [];
  const def = schema._def;
  const baseSchema = schema as BaseSchema<unknown>;

  // Description comment
  if (def.metadata.description) {
    lines.push(`# ${def.metadata.description}`);
  }

  // Required status
  const isRequired = !def.isOptional && def.defaultValue === undefined;
  if (def.defaultValue !== undefined) {
    lines.push(
      `# Required: no (default: ${formatDefaultValue(def.defaultValue)})`
    );
  } else if (def.isOptional) {
    lines.push("# Required: no");
  } else {
    lines.push("# Required: yes");
  }

  // Enum options
  if (def.enumValues && def.enumValues.length > 0) {
    lines.push(`# Options: ${def.enumValues.join(" | ")}`);
  }

  // Type hint for JSON
  if (def.type === "json") {
    lines.push("# Format: JSON");
  }

  // Secret warning
  if (def.metadata.isSecret) {
    lines.push("# ⚠️  This is a secret - do not commit real values");
  }

  // The actual variable line
  const example = baseSchema.getExample();
  const displayValue = def.metadata.isSecret ? "your_secret_here" : example;

  if (isRequired) {
    lines.push(`${name}=${displayValue}`);
  } else {
    // Optional or has default - show commented
    lines.push(`# ${name}=${displayValue}`);
  }

  return lines;
}

/**
 * Format a default value for display
 */
function formatDefaultValue(value: unknown): string {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value instanceof URL) {
    return value.toString();
  }
  return JSON.stringify(value);
}

/**
 * Write .env.example file
 */
export function writeExampleFile<T extends EnvSchema>(
  schema: T,
  options: GenerateOptions = {}
): { success: boolean; path: string; message: string } {
  const outputPath = options.output ?? ".env.example";
  const absolutePath = path.resolve(process.cwd(), outputPath);

  // Check if file exists
  if (fs.existsSync(absolutePath) && !options.force) {
    return {
      success: false,
      path: absolutePath,
      message: `File already exists: ${outputPath}. Use --force to overwrite.`,
    };
  }

  // Generate content
  const content = generateExampleContent(schema, options);

  // Write file
  try {
    fs.writeFileSync(absolutePath, content, "utf-8");
    return {
      success: true,
      path: absolutePath,
      message: `Generated ${outputPath}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return {
      success: false,
      path: absolutePath,
      message: `Failed to write file: ${message}`,
    };
  }
}

/**
 * Convenience function to generate example file
 */
export function generateExample<T extends EnvSchema>(
  schema: T,
  options: GenerateOptions = {}
): string {
  return generateExampleContent(schema, options);
}
